// src/generators/package-scripts-generator.ts
// Updates the target RN app package.json with environment run/build scripts
// and generates a Gradle variant health-check helper.

import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import { GeneratorContext, GenerationResult } from '../types/index.js';
import { logDry, normalizeEnvName } from '../utils/file-utils.js';

const PACKAGE_JSON_PATH = 'package.json';
const GRADLE_HEALTH_SCRIPT_PATH = 'scripts/gradle-health-check.cjs';

export async function generatePackageScripts(ctx: GeneratorContext): Promise<GenerationResult> {
  const result: GenerationResult = {
    success: false,
    filesModified: [],
    filesCreated: [],
    commands: [],
    warnings: [],
    errors: [],
  };

  const packageJsonPath = path.join(ctx.projectRoot, PACKAGE_JSON_PATH);
  if (!fs.existsSync(packageJsonPath)) {
    result.warnings.push(`Skipping package scripts: ${PACKAGE_JSON_PATH} not found.`);
    result.success = true;
    return result;
  }

  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8')) as Record<string, unknown>;
  } catch (e: unknown) {
    result.errors.push(`Failed to parse ${PACKAGE_JSON_PATH}: ${e instanceof Error ? e.message : String(e)}`);
    return result;
  }

  const currentScripts = (pkg.scripts as Record<string, string> | undefined) ?? {};
  const generatedScripts = buildGeneratedScripts(ctx);
  const nextScripts = { ...currentScripts, ...generatedScripts };

  const scriptsChanged = JSON.stringify(currentScripts) !== JSON.stringify(nextScripts);
  if (scriptsChanged) {
    if (ctx.dryRun) {
      logDry(`Would modify: ${PACKAGE_JSON_PATH}`);
      for (const [name, command] of Object.entries(generatedScripts)) {
        logDry(`  script: ${name} = ${command}`);
      }
    } else {
      pkg.scripts = nextScripts;
      fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf-8');
      result.filesModified.push(PACKAGE_JSON_PATH);
      console.log(chalk.green(`  ✔ Updated scripts in ${PACKAGE_JSON_PATH}`));
    }
  }

  const gradleHealthScript = buildGradleHealthScript(ctx);
  const gradleHealthPath = path.join(ctx.projectRoot, GRADLE_HEALTH_SCRIPT_PATH);
  const relHealthPath = GRADLE_HEALTH_SCRIPT_PATH;
  const healthScriptExisted = fs.existsSync(gradleHealthPath);

  if (ctx.dryRun) {
    logDry(`Would create/update: ${relHealthPath}`);
  } else {
    await fs.ensureDir(path.dirname(gradleHealthPath));
    fs.writeFileSync(gradleHealthPath, gradleHealthScript, 'utf-8');
    if (!healthScriptExisted) {
      result.filesCreated.push(relHealthPath);
    } else {
      result.filesModified.push(relHealthPath);
    }
    console.log(chalk.green(`  ✔ Wrote ${relHealthPath}`));
  }

  result.success = true;
  return result;
}

function buildGeneratedScripts(ctx: GeneratorContext): Record<string, string> {
  const scripts: Record<string, string> = {};
  const appName = ctx.config.appName;
  const needsEnvFile = ctx.config.jsEnvStrategy === 'react-native-config' || ctx.config.jsEnvStrategy === 'dotenv';

  for (const env of ctx.config.environments) {
    const envKey = normalizeEnvName(env.name);
    const envCap = capitalize(envKey);
    const envPrefix = needsEnvFile ? `ENVFILE=.env.${envKey} ` : '';

    scripts[`env:android:run:${envKey}`] = `${envPrefix}react-native run-android --variant=${envKey}Debug`;
    scripts[`env:android:apk:${envKey}:debug`] = `cd android && ./gradlew assemble${envCap}Debug`;
    scripts[`env:android:apk:${envKey}:release`] = `cd android && ./gradlew assemble${envCap}Release`;
    scripts[`env:android:aab:${envKey}:release`] = `cd android && ./gradlew bundle${envCap}Release`;
    scripts[`env:ios:run:${envKey}`] = `${envPrefix}react-native run-ios --scheme ${appName}-${envCap}`;
  }

  scripts['env:health:gradle'] = `node ${GRADLE_HEALTH_SCRIPT_PATH}`;
  return scripts;
}

function buildGradleHealthScript(ctx: GeneratorContext): string {
  const envKeys = ctx.config.environments.map((env) => normalizeEnvName(env.name));
  const envCaps = envKeys.map((env) => capitalize(env));

  return `#!/usr/bin/env node
// Auto-generated by rn-env-setup. Verifies Gradle flavor variants/tasks exist.

const { execSync } = require('node:child_process');

const FLAVORS = ${JSON.stringify(envCaps, null, 2)};
const EXPECTED_TASKS = FLAVORS.flatMap((flavor) => [
  \`assemble\${flavor}Debug\`,
  \`assemble\${flavor}Release\`,
  \`bundle\${flavor}Release\`,
]);

function runGradleTasks() {
  try {
    return execSync('./gradlew tasks --all', { cwd: 'android', stdio: 'pipe', encoding: 'utf-8' });
  } catch (error) {
    const stderr = error && typeof error === 'object' ? error.stderr : '';
    const message = String(stderr || error);
    console.error('Gradle health check failed to execute ./gradlew tasks --all');
    console.error(message);
    process.exit(1);
  }
}

const tasksOutput = runGradleTasks();
const missing = EXPECTED_TASKS.filter((task) => !new RegExp(\`\\\\b\${task}\\\\b\`).test(tasksOutput));

if (missing.length > 0) {
  console.error('Gradle health check failed. Missing expected flavor/variant tasks:');
  for (const task of missing) {
    console.error(\`  - \${task}\`);
  }
  process.exit(1);
}

console.log('Gradle health check passed. All expected flavor/variant tasks are present.');
`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
